version: 0.0
os: linux

files:
  - source: files/hello.txt
    destination: /home/ubuntu/

permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/sleep.sh
    
  AfterInstall:
    - location: scripts/start_python.sh
